import os
import sys
import django
import random
from datetime import timedelta
from django.utils import timezone

# Setup Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'machine_management.settings')
django.setup()

from accounts.models import Machine_Logs, Machine
from django.contrib.auth.models import User

def seed():
    # 1. Ensure at least one User exists
    user = User.objects.first()
    if not user:
        print("Creating default admin user...")
        user = User.objects.create_superuser('admin', 'admin@gmail.com', 'admin123')

    # 2. Ensure at least one Machine exists
    machine = Machine.objects.first()
    if not machine:
        print("Creating default Machine...")
        machine = Machine.objects.create(
            user=user,
            name="Default Machine",
            description="Generated by seed script"
        )

    print("Clearing old Machine_Logs...")
    Machine_Logs.objects.all().delete()
    
    print("Seeding new Machine_Logs for the last 7 days...")
    
    now = timezone.now()
    logs_to_create = []

    # Columns to check for errors according to user requirements
    error_columns = [
        'caminput', 'grayfilter', 'shape01', 'pos01', 'label01', 
        'switch01', 'pos02', 'switch02', 'resultdisplay', 'shape02'
    ]

    # Loop from 6 days ago up to today (total 7 days)
    for day_offset in range(6, -1, -1):
        target_day = now - timedelta(days=day_offset)
        
        # Create between 50 to 120 items per day
        num_logs = random.randint(50, 120)
        
        for _ in range(num_logs):
            random_hour = random.randint(0, 23)
            random_minute = random.randint(0, 59)
            log_time = target_day.replace(hour=random_hour, minute=random_minute, second=0, microsecond=0)
            
            # Logic: 80% pass, 20% fail
            is_pass = random.random() < 0.8
            
            # Initialize all check columns with 1 (Pass)
            row_data = {col: 1 for col in error_columns}
            
            if not is_pass:
                # If fail, randomly pick 1 to 3 columns to set to -1
                num_faults = random.randint(1, 3)
                fault_cols = random.sample(error_columns, num_faults)
                for col in fault_cols:
                    row_data[col] = -1
            
            log = Machine_Logs(
                machine=machine,
                process_time_ms=round(random.uniform(55.0, 65.0), 2),
                **row_data,
                posx01=random.randint(100, 200),
                posy01=random.randint(100, 200),
                posx02=random.randint(100, 200),
                posy02=random.randint(100, 200),
                totalarea01=random.randint(1000, 2000),
                numoflabels01=1
            )
            # Create a separate step to set timestamps since bulk_create is used
            log.created = log_time
            logs_to_create.append(log)
            
    Machine_Logs.objects.bulk_create(logs_to_create)
    print(f"Successfully seeded {len(logs_to_create)} logs across the last 7 days!")

if __name__ == '__main__':
    seed()
