# Generated by Django 5.2.10 on 2026-03-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_logs',
            name='type_error',
            field=models.CharField(choices=[('missing_component', 'Missing Component'), ('misplaced_component', 'Misplaced Component'), ('soldering_defect', 'Soldering Defect'), ('missing_pin', 'Missing Pin'), ('defective_label', 'Misaligned/Missing Label'), ('wrong_shape_or_polarity', 'Wrong Shape/Polarity')], default='missing_component', max_length=100),
        ),
    ]
