# Generated by Django 5.2.10 on 2026-03-10 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_machine_logs_result_alter_machine_logs_type_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_logs',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
