# Generated by Django 5.2.10 on 2026-03-18 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_logs',
            name='code_product',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='result',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='type_error',
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='caminput',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='grayfilter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='label01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='pos01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='pos02',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='process_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='resultdisplay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='shape01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='shape02',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='switch01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='switch02',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.machine'),
        ),
    ]
