# Generated by Django 5.2.10 on 2026-03-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_machine_logs_code_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_logs',
            name='circuit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='caminput',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='grayfilter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='label01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='pos01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='pos02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='process_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='resultdisplay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='shape01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='shape02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='switch01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_logs',
            name='switch02',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
