# Generated by Django 5.2.10 on 2026-03-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_machine_logs_circuit_id_alter_machine_logs_caminput_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_logs',
            name='circuit_id',
        ),
    ]
