# Generated by Django 5.2.10 on 2026-04-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_machine_logs_circuit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_logs',
            name='numoflabels01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='posx01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='posx02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='posy01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='posy02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='totalarea01',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
