# Generated by Django 5.2.10 on 2026-04-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_machine_logs_numoflabels01_machine_logs_posx01_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_logs',
            name='status',
        ),
    ]
