# Generated by Django 5.2.10 on 2026-05-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_machine_logs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_logs',
            name='caminput',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='grayfilter',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='label01',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='numoflabels01',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='pos01',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='pos02',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='posx01',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='posx02',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='posy01',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='posy02',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='process_time_ms',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='resultdisplay',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='shape01',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='shape02',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='switch01',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='switch02',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='totalarea01',
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='misaligned_component',
            field=models.IntegerField(blank=True, help_text='Số lượng linh kiện bị lệch vị trí', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='misaligned_component_conf',
            field=models.FloatField(blank=True, help_text='Độ tin cậy của việc phát hiện linh kiện bị lệch (0 -> 1)', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='missing_component',
            field=models.IntegerField(blank=True, help_text='Số lượng linh kiện bị thiếu', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='missing_component_conf',
            field=models.FloatField(blank=True, help_text='Độ tin cậy khi phát hiện linh kiện bị thiếu', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='missing_label',
            field=models.IntegerField(blank=True, help_text='Số lượng nhãn (label) bị thiếu', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='missing_label_conf',
            field=models.FloatField(blank=True, help_text='Độ tin cậy của việc phát hiện thiếu nhãn', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='missing_pin',
            field=models.IntegerField(blank=True, help_text='Số lượng chân (pin) bị thiếu', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='missing_pin_conf',
            field=models.FloatField(blank=True, help_text='Độ tin cậy khi phát hiện thiếu chân pin', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Thời gian xử lý', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='wrong_polarity',
            field=models.IntegerField(blank=True, help_text='Số lượng linh kiện bị sai cực', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='wrong_polarity_conf',
            field=models.FloatField(blank=True, help_text='Độ tin cậy của việc phát hiện sai cực', null=True),
        ),
    ]
