# Generated by Django 5.2.10 on 2026-05-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_machine_logs_caminput_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine_logs',
            old_name='processing_time',
            new_name='ProcessingTime',
        ),
        migrations.RenameField(
            model_name='machine_logs',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='machine_logs',
            old_name='misaligned_component_conf',
            new_name='misaligned_component_Conf',
        ),
        migrations.RenameField(
            model_name='machine_logs',
            old_name='missing_component_conf',
            new_name='missing_component_Conf',
        ),
        migrations.RenameField(
            model_name='machine_logs',
            old_name='missing_label_conf',
            new_name='missing_label_Conf',
        ),
        migrations.RenameField(
            model_name='machine_logs',
            old_name='missing_pin_conf',
            new_name='missing_pin_Conf',
        ),
        migrations.RenameField(
            model_name='machine_logs',
            old_name='wrong_polarity',
            new_name='wrong_polarrity',
        ),
        migrations.RenameField(
            model_name='machine_logs',
            old_name='wrong_polarity_conf',
            new_name='wrong_polarrity_Conf',
        ),
    ]
