# Generated by Django 5.2.10 on 2026-05-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_status_machine_logs_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_logs',
            name='misaligned_component',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='misaligned_component_Conf',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='missing_label',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='missing_label_Conf',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='missing_pin',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='missing_pin_Conf',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='wrong_polarity',
        ),
        migrations.RemoveField(
            model_name='machine_logs',
            name='wrong_polarity_Conf',
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='empty',
            field=models.IntegerField(blank=True, help_text='Lỗi trống (empty)', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='empty_Conf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='excess_solder',
            field=models.IntegerField(blank=True, help_text='Lỗi hàn dư', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='excess_solder_Conf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='exposed_copper',
            field=models.IntegerField(blank=True, help_text='Lỗi hở đồng', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='exposed_copper_Conf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='misaligned_header',
            field=models.IntegerField(blank=True, help_text='Lỗi lệch header', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='misaligned_header_Conf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='scratched',
            field=models.IntegerField(blank=True, help_text='Lỗi trầy xước', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='scratched_Conf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='solder_bridge',
            field=models.IntegerField(blank=True, help_text='Lỗi cầu hàn', null=True),
        ),
        migrations.AddField(
            model_name='machine_logs',
            name='solder_bridge_Conf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
