# Generated by Codex on 2026-05-06

from django.db import migrations, models


def normalize_status(apps, schema_editor):
    MachineLogs = apps.get_model('accounts', 'Machine_Logs')

    # Normalize common string values to '0'/'1'
    MachineLogs.objects.filter(Status__iexact='OK').update(Status='0')
    MachineLogs.objects.filter(Status__iexact='NG').update(Status='1')


    # Normalize any remaining values (trim, map)
    rows = MachineLogs.objects.exclude(Status__in=['0', '1']).exclude(Status__isnull=True).values('id', 'Status')
    for row in rows.iterator():
        raw = (row['Status'] or '').strip()
        if raw.lower() == 'ok':
            normalized = '0'
        elif raw.lower() == 'ng':
            normalized = '1'
        elif raw in ['0', '1']:
            normalized = raw
        else:
            # Unknown value: keep as-is to avoid data loss
            continue

        MachineLogs.objects.filter(id=row['id']).update(Status=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_machine_logs_misaligned_component_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='machine_logs',
            name='Status',
            field=models.CharField(
                blank=True,
                choices=[('0', 'OK'), ('1', 'NG')],
                default='0',
                help_text='0 = OK (no error), 1 = NG (has error)',
                max_length=1,
                null=True,
            ),
        ),
    ]
